name: Wired Brain Workflow

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore Dependencies
      run: dotnet restore

    - id: build
      name: Build      
      run: dotnet build --no-restore
    
    # This function processes the selected code and generates a documentation comment
    # in YAML format, as per the user's request. It ensures that only the documentation
    # comment is returned, without repeating the original code. The documentation
    # provides a clear and concise explanation of the function's purpose and usage.

    
    
  
      